# Generated by Django 5.2.8 on 2025-11-14 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=100)),
                ('total_exam_points', models.IntegerField(default=0)),
                ('passing_percentage', models.FloatField(default=75.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerKeySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('items', models.JSONField(default=list)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_sections', to='api.exam')),
            ],
        ),
    ]
