# Generated by Django 5.2.8 on 2025-11-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_examsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubmission',
            name='total_points',
        ),
    ]
