# Generated by Django 5.2.8 on 2025-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_examsubmission_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmission',
            name='score',
            field=models.IntegerField(),
        ),
    ]
