# Generated by Django 5.2.8 on 2025-11-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_examsubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='section_scores',
            field=models.JSONField(blank=True, default=list, help_text="List of per-section scores: [{'sectionTitle': 'MCQ', 'score': 10, 'total': 15}]"),
        ),
    ]
