# Generated by Django 5.2.8 on 2025-11-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_examsubmission_section_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsubmission',
            old_name='passed',
            new_name='status',
        ),
    ]
